[build]
  base = "client/"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://tu-backend-url.railway.app/api"

[[redirects]]
  from = "/api/*"
  to = "https://tu-backend-url.railway.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
