-- Supabase RLS policies for a client-only app
-- Run this in the Supabase SQL editor (or psql) after creating the tables.

-- Ensure required extensions (optional depending on your DB setup)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enable Row Level Security
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- USERS table policies
-- Allow users to select only their own user row
CREATE POLICY "Users - select own" ON public.users
  FOR SELECT
  USING (auth.uid() = id);

-- Allow users to insert their own user record (used by signUp flows)
CREATE POLICY "Users - insert own" ON public.users
  FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Allow users to update their own profile
CREATE POLICY "Users - update own" ON public.users
  FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- TODOS table policies
-- Allow logged-in users to select their own todos
CREATE POLICY "Todos - select own" ON public.todos
  FOR SELECT
  USING (auth.uid() = user_id);

-- Allow users to insert todos setting user_id to their auth id
CREATE POLICY "Todos - insert own" ON public.todos
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Allow users to update their own todos
CREATE POLICY "Todos - update own" ON public.todos
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Allow users to delete their own todos
CREATE POLICY "Todos - delete own" ON public.todos
  FOR DELETE
  USING (auth.uid() = user_id);

-- Optional: restrict public.schema default grants if necessary
-- Revoke public access to tables (Supabase may manage these grants)
-- REVOKE ALL ON TABLE public.todos FROM public;
-- REVOKE ALL ON TABLE public.users FROM public;

-- Notes:
-- 1. Use the anon (public) key in the frontend. Never expose the service_role key.
-- 2. If your "id" columns are generated by auth, ensure inserts use the auth.uid() value.
-- 3. After running policies, test with an incognito session and the anon key to verify access.
